spring.application.name=kmc2024
spring.datasource.url=jdbc:mariadb://irafe.com:3306/web2024?user=web2024&password=qwerasdf
server.servlet.context-path=/web2024
# ???, html, css, javascript 에서 한글이 제대로 나옴
server.servlet.encoding.force=true